GET http://localhost:3000/states/
###
GET http://localhost:3000/states/3/
###
POST http://localhost:3000/districts/
Content-Type:application/json 

{
"stateId":3,
  "districtName":"Bagalkot",
  "casesNumber":2323,
  "curedNumber":2000,
  "activeNumber":315,
  "deathsNumber":8
}
###
GET http://localhost:3000/districts/6/
###
DELETE http://localhost:3000/districts/5/
###
PUT http://localhost:3000/districts/5/
Content-Type:application/json 

{
     "districtName": "Nadia",
  "stateId": 3,
  "casesNumber": 9628,
  "curedNumber": 6524,
  "activeNumber": 3000,
  "deathsNumber": 104
}
###
GET http://localhost:3000/states/4/stats/
###
GET http://localhost:3000/districts/5/